services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - static_volume:/app/staticfile
      - media_volume:/app/mediafile
    expose:
      - "8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres
      - mailhog
      - redis
    command: /start
    networks:
      - author-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - author-api

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - author-api

  redis:
    image : redis:7-alpine
    networks:
      - author-api

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /scripts/start-celeryworker


    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

    depends_on:
      - redis
      - postgres
      - mailhog
    networks:
      - author-api

  
  flower:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /scripts/start-flower

    volumes:
      - flower_data:/data
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

    ports:
      - "5555:5555"

    depends_on:
      - redis
      - postgres

    networks:
      - author-api
  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfile
      - media_volume:/app/mediafiles
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - author-api



networks:
  author-api:
    driver: bridge

volumes:
  static_volume: {}
  media_volume: {}
  local_postgres_data: {}
  local_postgres_data_backups: {}
  flower_data: {}