[tool.black]
line-length = 88
target-version = ["py311"]
extend-exclude = '''
(
/(
    \.eggs
    | \.git
    | \.mypy_cache
    | \.envs
    | \.tox
    | \.venv
    | ven
    | venv
    | build
    )/
)
'''
[tool.isort]
profile = "black"
[tool.flack8]
ignore = "E203,E501,W503"
max-line-length = 120