#!/bin/bash

set -o errexit
set -o nounset

# Run Flower with basic auth using env vars
exec celery \
  -A config.celery \
  flower \
  --broker="${CELERY_BROKER}" \
  --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
